// Vercel build script — generates supabase-config.js from environment variables
// Set in Vercel Dashboard > Project > Settings > Environment Variables:
//   SUPABASE_URL   → Your Supabase project URL
//   SUPABASE_ANON  → Your Supabase anon/public key
//   ADMIN_EMAIL    → Admin user email address

const fs = require('fs');

const url   = process.env.SUPABASE_URL;
const anon  = process.env.SUPABASE_ANON;
const admin = process.env.ADMIN_EMAIL;

if (!url || !anon || !admin) {
  console.error('ERROR: Missing required environment variables:');
  if (!url)   console.error('  - SUPABASE_URL');
  if (!anon)  console.error('  - SUPABASE_ANON');
  if (!admin) console.error('  - ADMIN_EMAIL');
  process.exit(1);
}

const content = `// Allboard — Supabase Configuration (auto-generated by build.js)
// Do NOT edit this file directly. Set environment variables in Vercel.

const SUPABASE_URL  = '${url}';
const SUPABASE_ANON = '${anon}';
const ADMIN_EMAIL   = '${admin}';

const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});

async function getSession() {
  const { data: { session } } = await sb.auth.getSession();
  return session;
}

async function isAdmin() {
  const session = await getSession();
  if (!session) return false;
  return session.user.email === ADMIN_EMAIL;
}
`;

fs.writeFileSync('supabase-config.js', content);
console.log('supabase-config.js generated successfully.');
